### ISSUE TITLE
more concise versions of Nat.fromInt

### ISSUE THREAD

**Issue by indique** [obiloud/numeric-decimal#2]
If you call `Nat.fromInt`, what should you expect?
The doc says
> Nat from Int
- does it return `nat0` for negative values?
- does it return the absolute value?
- or might this even be unsafe?

I'd suggest
- replacing `fromInt` with `fromAbs` or `fromIntAbs`
- and maybe adding `or0IfNegative` or `fromIntOr0` or something else

**Comment by obiloud** [comment]
@indique thanks for the feedback. I really didn't give this much thought, Big up ❤️

**Comment by obiloud** [comment]
Renamed  `fromInt` with `fromIntAbs` and added documentation with examples. 
Added `fromIntOrZero` with documentation and examples.
