### ISSUE TITLE
Rational.power of negative Ints behaves unexpectedly

### ISSUE THREAD

**Issue by indique** [obiloud/numeric-decimal#3]
I'd expect `fromInt 2 |> power -2` to be `ratio 1 4`.
Instead, it is `ratio 0.25 1`.

Funnily enough, this is a problem of the `^` operator in elm.
```elm
power : Int -> Rational -> Rational
power pow (Rational n d) =
    ratio (n ^ pow) d
```
It allows you to say `Int ^ Int` is an `Int` which is not always true.

A suggestion
```elm
power pow (Rational n d) =
    if pow >= 0 then
        ratio (n ^ pow) d
    else
        inverse (power (abs pow) (ratio n d))
```
You might also think about how to handle `0 ^ 0`.

**Comment by obiloud** [comment]
I cannot confirm this from my tests.

```elm
    Expect.equal (R.fromInt 2 |> R.power -2) (R.ratio 1 4)
```
```elm
    Expect.equal (R.fromInt 2 |> R.power -2 |> R.toString) (R.ratio 1 4 |> R.toString)
```
```elm
    R.fromInt 2 |> R.power -2 |> R.toString |> Debug.log "ratio"   --ratio: "1/4"
```

**Comment by indique** [comment]
You are right. `Numeric.Integer.div` seems to be able to handle the division of `Int`s that are actually floating point numbers.
Sorry for opening this issue.
