### ISSUE TITLE
(n/d)^p = (n^p)/(d^p)

### ISSUE THREAD

**Issue by ccomb** [obiloud/numeric-decimal#4]
Hi
```
power : Int -> Rational -> Rational
power pow (Rational n d) =
    ratio (n ^ pow) d
```

I'd tend to replace with:

```
power : Int -> Rational -> Rational
power pow (Rational n d) =
    ratio (n ^ pow) (d ^ pow)
```

Am I wrong?

**Comment by obiloud** [comment]
@ccomb Sorry, you are looking at this wrong. Think of a rational as a fraction: n here stands for the nominator, and d stands for the denominator.

**Comment by obiloud** [comment]
@ccomb Thanks for pointing this out. This was an oversight on my part.
